### ISSUE TITLE
How to set up Sentinel data

### ISSUE THREAD

**Issue by marksev1** [styluslabs/maps#1]
Hi, I'm just beta testing the app. It's great, can't wait to test the 3D mapping functionality. I'm also excited about the Sentinel satellite data, though I don't know how to configure it?

**Comment by pbsurf** [comment]
See the comment at the top of [plugins/sentinel2.js](https://github.com/styluslabs/maps/blob/master/assets/plugins/sentinel2.js) for instructions.  There are a few open servers which provide recent low-cloud Sentinel tiles, but using copernicus.eu directly makes it possible to explicitly specify the maximum age and cloud cover.

**Comment by marksev1** [comment]
Thanks! Got a follow up question, where do I find _secrets.js  in the android file system?

**Comment by pbsurf** [comment]
You'll have to create the file _secrets.js (leading underscore since plugins loaded in alphabetical order) in the plugins/ folder containing, for example, `secrets = { "sentinel2_id": "<sentinel2 id goes here>" };`

Depending on what device and version of Android you have, getting write access to the /Android/data/com.styluslabs.maps/ folder might be tricky.  MiXplorer API-29 version + uninstalling updates to built-in Google Files app worked for me.  Originally I tried to use the more accessible /Android/media folder instead of /Android/data, but file I/O is much slower in /Android/media.  I may eventually (have to) support merging in user edited files from /Android/media or something.

**Comment by marksev1** [comment]
I tried it, its cool! It works with MiXplorer without issue. Perhaps, if one could add the id via some prompt from the user-interface, that would make it easier for users, though as I said for me it went without issue.

Perhaps as a feature request it would be cool if one could browse through the last 6 or 7 satellite from the area and with some buttons move through them, to see which one is clearest for the area of choice.

Otherwise awesome stuff!
